- job:
    name: manila-test-image-build
    parent: unittests
    required-projects:
      - openstack/manila-test-image
    run: playbooks/manila-test-image-build/run.yaml
    timeout: 1800

- project:
    check:
      jobs:
        - openstack-tox-bashate
    gate:
      jobs:
        - openstack-tox-bashate
    experimental:
      jobs:
        - manila-test-image-build
