- job:
    name: manila-test-image-build
    parent: legacy-base
    run: playbooks/manila-test-image-build/run.yaml
    timeout: 3600

- project:
    check:
      jobs:
        - openstack-tox-bashate
    gate:
      jobs:
        - openstack-tox-bashate
    experimental:
      jobs:
        - manila-test-image-build
